# Generated by Django 4.2.5 on 2023-11-06 18:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userlocation", "0002_alter_profile_lat_alter_profile_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
