# Generated by Django 4.2.5 on 2023-11-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userlocation", "0003_profile_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landmarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
