# Generated by Django 4.2.5 on 2023-11-08 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userlocation", "0004_landmarks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Landmarks",
            new_name="Landmark",
        ),
    ]
