# Generated by Django 4.2.5 on 2023-11-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userlocation", "0006_delete_location_landmark_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
