# Generated by Django 3.2.19 on 2023-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlocation', '0008_profile_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='landmark',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
